<?xml version="1.0"?>
<package format="3">
  <name>sw01_slam</name>
  <version>0.0.0</version>
  <description>SW01 SLAM launch and configuration resources.</description>
  <maintainer email="sw01@example.com">SW01</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>fast_lio</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
